export interface StemCenter {
    id: string
    name: string
    host: string
    city: string
    country: string
    latitude: number
    longitude: number
  }
  
  export const ethiopiaStemCenters: StemCenter[] = [
    {
      id: "1",
      name: "Foka STEM Training Center",
      host: "Foka STEM Training Center",
      city: "Bishoftu",
      country: "Ethiopia",
      latitude: 8.7969,
      longitude: 39.2333,
    },
    {
      id: "2",
      name: "Kallamino Special High School STEM Center",
      host: "Kallamino Special High School",
      city: "Mekelle",
      country: "Ethiopia",
      latitude: 13.4981,
      longitude: 39.4803,
    },
    {
      id: "3",
      name: "Gondar University STEM Center",
      host: "Gondar University",
      city: "Gondar",
      country: "Ethiopia",
      latitude: 12.6047,
      longitude: 37.4669,
    },
    {
      id: "4",
      name: "Addis Ababa Science & Technology University STEM Center",
      host: "AASTU",
      city: "Addis Ababa",
      country: "Ethiopia",
      latitude: 9.032,
      longitude: 38.7469,
    },
    {
      id: "5",
      name: "Bahirdar University STEM Center",
      host: "Bahirdar University",
      city: "Bahirdar",
      country: "Ethiopia",
      latitude: 11.5951,
      longitude: 37.3888,
    },
    {
      id: "6",
      name: "AASTU Science Museum",
      host: "AASTU Science Museum",
      city: "Addis Ababa",
      country: "Ethiopia",
      latitude: 9.032,
      longitude: 38.7469,
    },
    {
      id: "7",
      name: "Hawassa University STEM Center",
      host: "Hawassa University",
      city: "Hawassa",
      country: "Ethiopia",
      latitude: 5.0269,
      longitude: 38.4806,
    },
    {
      id: "8",
      name: "Jigjiga University STEM Center",
      host: "Jigjiga University",
      city: "Jigjiga",
      country: "Ethiopia",
      latitude: 9.3505,
      longitude: 40.2789,
    },
    {
      id: "9",
      name: "Asosa University STEM Center",
      host: "Asosa University",
      city: "Asossa",
      country: "Ethiopia",
      latitude: 10.7667,
      longitude: 34.5333,
    },
    {
      id: "10",
      name: "Wollega University STEM Center",
      host: "Wollega University",
      city: "Nekemet",
      country: "Ethiopia",
      latitude: 9.1167,
      longitude: 34.2667,
    },
    {
      id: "11",
      name: "Kotebe Science Shared Campus STEM Center",
      host: "Kotebe Science Shared Campus",
      city: "Addis Ababa",
      country: "Ethiopia",
      latitude: 9.032,
      longitude: 38.7469,
    },
    {
      id: "12",
      name: "Asaita High School STEM Center",
      host: "Asaita High School",
      city: "Asaita",
      country: "Ethiopia",
      latitude: 11.1167,
      longitude: 40.45,
    },
    {
      id: "13",
      name: "Adama Science & Technology University STEM Center",
      host: "Adama Science & Technology University",
      city: "Adama",
      country: "Ethiopia",
      latitude: 8.5384,
      longitude: 39.2675,
    },
    {
      id: "14",
      name: "Liqa Special School STEM Center",
      host: "Liqa Special School",
      city: "Wolaita",
      country: "Ethiopia",
      latitude: 6.8,
      longitude: 37.7667,
    },
    {
      id: "15",
      name: "Haromaya University STEM Center",
      host: "Haromaya University",
      city: "Haromaya",
      country: "Ethiopia",
      latitude: 9.2167,
      longitude: 41.9833,
    },
    {
      id: "16",
      name: "Gode Polytechnic College STEM Center",
      host: "Gode Polytechnic College",
      city: "Gode",
      country: "Ethiopia",
      latitude: 5.9667,
      longitude: 43.5167,
    },
    {
      id: "17",
      name: "Harar Aboker Secondary School STEM Center",
      host: "Harar Aboker Secondary School",
      city: "Harari",
      country: "Ethiopia",
      latitude: 9.3167,
      longitude: 42.1333,
    },
    {
      id: "18",
      name: "Woldia University STEM Center",
      host: "Woldia University",
      city: "Woldia",
      country: "Ethiopia",
      latitude: 11.8333,
      longitude: 39.6,
    },
    {
      id: "19",
      name: "Ethiopian Academy of Sciences STEM Center",
      host: "Ethiopian Academy of Sciences",
      city: "Addis Ababa",
      country: "Ethiopia",
      latitude: 9.032,
      longitude: 38.7469,
    },
    {
      id: "20",
      name: "Addis Ababa Institute of Technology (AAiT) STEM Center",
      host: "AAiT",
      city: "Addis Ababa",
      country: "Ethiopia",
      latitude: 9.032,
      longitude: 38.7469,
    },
    {
      id: "21",
      name: "Wollo University STEM Center",
      host: "Wollo University",
      city: "Dessie",
      country: "Ethiopia",
      latitude: 11.1333,
      longitude: 39.6333,
    },
    {
      id: "22",
      name: "Debre Berhan University STEM Center",
      host: "Debre Berhan University",
      city: "Debre Berhan",
      country: "Ethiopia",
      latitude: 9.6667,
      longitude: 39.5333,
    },
    {
      id: "23",
      name: "Debre Markos University STEM Center",
      host: "Debre Markos University",
      city: "Debre Markos",
      country: "Ethiopia",
      latitude: 10.3333,
      longitude: 37.6667,
    },
    {
      id: "24",
      name: "Dilla University STEM Center",
      host: "Dilla University",
      city: "Dilla",
      country: "Ethiopia",
      latitude: 6.3667,
      longitude: 38.3,
    },
    {
      id: "25",
      name: "Kebridahar University STEM Center",
      host: "Kebridahar University",
      city: "Kebridahar",
      country: "Ethiopia",
      latitude: 4.1833,
      longitude: 43.1667,
    },
    {
      id: "26",
      name: "Arba Minch University STEM Center",
      host: "Arba Minch University",
      city: "Arba Minch",
      country: "Ethiopia",
      latitude: 5.9833,
      longitude: 37.55,
    },
    {
      id: "27",
      name: "Dire Dawa University STEM Center",
      host: "Dire Dawa University",
      city: "Dire Dawa",
      country: "Ethiopia",
      latitude: 9.5833,
      longitude: 41.8667,
    },
    {
      id: "28",
      name: "Samara University STEM Center",
      host: "Samara University",
      city: "Samara",
      country: "Ethiopia",
      latitude: 11.2833,
      longitude: 40.9833,
    },
    {
      id: "29",
      name: "Mekdela Amba University STEM Center",
      host: "Mekdela Amba University",
      city: "Tulu Awuliya",
      country: "Ethiopia",
      latitude: 10.2,
      longitude: 38.8,
    },
    {
      id: "30",
      name: "Injibara University STEM Center",
      host: "Injibara University",
      city: "Injibara",
      country: "Ethiopia",
      latitude: 10.7667,
      longitude: 37.1667,
    },
    {
      id: "31",
      name: "Mizan Tepi University STEM Center",
      host: "Mizan Tepi University",
      city: "Mizan Teferi",
      country: "Ethiopia",
      latitude: 7.7333,
      longitude: 35.1,
    },
    {
      id: "32",
      name: "Bule Hora University STEM Center",
      host: "Bule Hora University",
      city: "Bule Hora",
      country: "Ethiopia",
      latitude: 5.5333,
      longitude: 38.3,
    },
    {
      id: "33",
      name: "Raya University STEM Center",
      host: "Raya University",
      city: "Maychew",
      country: "Ethiopia",
      latitude: 13.8,
      longitude: 39.5,
    },
    {
      id: "34",
      name: "Adigrat University STEM Center",
      host: "Adigrat University",
      city: "Adigrat",
      country: "Ethiopia",
      latitude: 14.2833,
      longitude: 39.4667,
    },
    {
      id: "35",
      name: "Aksum University STEM Center",
      host: "Aksum University",
      city: "Aksum",
      country: "Ethiopia",
      latitude: 14.1333,
      longitude: 38.7167,
    },
    {
      id: "36",
      name: "Oda Bultum University STEM Center",
      host: "Oda Bultum University",
      city: "Chiro",
      country: "Ethiopia",
      latitude: 9.3,
      longitude: 40.3,
    },
    {
      id: "37",
      name: "Mettu University STEM Center",
      host: "Mettu University",
      city: "Mettu",
      country: "Ethiopia",
      latitude: 8.3,
      longitude: 35.8,
    },
    {
      id: "38",
      name: "Dembi Dollo University STEM Center",
      host: "Dembi Dollo University",
      city: "Dembi Dollo",
      country: "Ethiopia",
      latitude: 8.7333,
      longitude: 34.8,
    },
    {
      id: "39",
      name: "Madda Walabu University STEM Center",
      host: "Madda Walabu University",
      city: "Bale Robe",
      country: "Ethiopia",
      latitude: 7.1667,
      longitude: 40.3,
    },
    {
      id: "40",
      name: "Wachemo University STEM Center",
      host: "Wachemo University",
      city: "Hossana",
      country: "Ethiopia",
      latitude: 7.5667,
      longitude: 37.8667,
    },
    {
      id: "41",
      name: "Wolaita Sodo University STEM Center",
      host: "Wolaita Sodo University",
      city: "Wolaita Sodo",
      country: "Ethiopia",
      latitude: 6.8333,
      longitude: 37.7667,
    },
    {
      id: "42",
      name: "Debre Tabor University STEM Center",
      host: "Debre Tabor University",
      city: "Debre Tabor",
      country: "Ethiopia",
      latitude: 11.8667,
      longitude: 38.0167,
    },
    {
      id: "43",
      name: "Semera University STEM Center",
      host: "Semera University",
      city: "Semera",
      country: "Ethiopia",
      latitude: 11.7833,
      longitude: 40.5167,
    },
    {
      id: "44",
      name: "Jinka University STEM Center",
      host: "Jinka University",
      city: "Jinka",
      country: "Ethiopia",
      latitude: 5.8667,
      longitude: 36.6667,
    },
    {
      id: "45",
      name: "Assosa Polytechnic College STEM Center",
      host: "Assosa Polytechnic College",
      city: "Assosa",
      country: "Ethiopia",
      latitude: 10.7667,
      longitude: 34.5333,
    },
    {
      id: "46",
      name: "Gambella University STEM Center",
      host: "Gambella University",
      city: "Gambella",
      country: "Ethiopia",
      latitude: 8.25,
      longitude: 34.5833,
    },
    {
      id: "47",
      name: "Salale University STEM Center",
      host: "Salale University",
      city: "Fitche",
      country: "Ethiopia",
      latitude: 9.8,
      longitude: 38.7333,
    },
    {
      id: "48",
      name: "Ambo University STEM Center",
      host: "Ambo University",
      city: "Ambo",
      country: "Ethiopia",
      latitude: 8.9833,
      longitude: 37.8667,
    },
    {
      id: "49",
      name: "Jimma University STEM Center",
      host: "Jimma University",
      city: "Jimma",
      country: "Ethiopia",
      latitude: 7.6667,
      longitude: 36.8333,
    },
    {
      id: "50",
      name: "Metu Polytechnic College STEM Center",
      host: "Metu Polytechnic College",
      city: "Metu",
      country: "Ethiopia",
      latitude: 8.3,
      longitude: 35.8,
    },
    {
      id: "51",
      name: "Nekemte Polytechnic College STEM Center",
      host: "Nekemte Polytechnic College",
      city: "Nekemte",
      country: "Ethiopia",
      latitude: 9.1167,
      longitude: 34.2667,
    },
    {
      id: "52",
      name: "Bonga University STEM Center",
      host: "Bonga University",
      city: "Bonga",
      country: "Ethiopia",
      latitude: 7.2667,
      longitude: 35.6333,
    },
    {
      id: "53",
      name: "Bench Maji Zone STEM Center",
      host: "Bench Maji Zone",
      city: "Mizan Aman",
      country: "Ethiopia",
      latitude: 7.7,
      longitude: 35.1167,
    },
    {
      id: "54",
      name: "Gedeo Zone STEM Center",
      host: "Gedeo Zone",
      city: "Dilla",
      country: "Ethiopia",
      latitude: 6.3667,
      longitude: 38.3,
    },
    {
      id: "55",
      name: "Konso Special Woreda STEM Center",
      host: "Konso Special Woreda",
      city: "Konso",
      country: "Ethiopia",
      latitude: 5.2667,
      longitude: 37.1,
    },
    {
      id: "56",
      name: "Segen Area Peoples Zone STEM Center",
      host: "Segen Area Peoples Zone",
      city: "Arba Minch",
      country: "Ethiopia",
      latitude: 5.9833,
      longitude: 37.55,
    },
    {
      id: "57",
      name: "Gurage Zone STEM Center",
      host: "Gurage Zone",
      city: "Welkite",
      country: "Ethiopia",
      latitude: 8.6,
      longitude: 37.8,
    },
    {
      id: "58",
      name: "Hadiya Zone STEM Center",
      host: "Hadiya Zone",
      city: "Hossana",
      country: "Ethiopia",
      latitude: 7.5667,
      longitude: 37.8667,
    },
    {
      id: "59",
      name: "Silte Zone STEM Center",
      host: "Silte Zone",
      city: "Silte",
      country: "Ethiopia",
      latitude: 8.1,
      longitude: 37.9,
    },
    {
      id: "60",
      name: "East Gojjam Zone STEM Center",
      host: "East Gojjam Zone",
      city: "Debre Markos",
      country: "Ethiopia",
      latitude: 10.3333,
      longitude: 37.6667,
    },
    {
      id: "61",
      name: "West Gojjam Zone STEM Center",
      host: "West Gojjam Zone",
      city: "Finote Selam",
      country: "Ethiopia",
      latitude: 10.3667,
      longitude: 36.6667,
    },
  ]
  